# -*- coding: utf-8 -*-
"""API-FLASK-DIO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MLj9gX2vbPf-PNaT8uHxCS_EbmEeRyj
"""

!pip install flask_ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as rk

data = [{
    "id": 1,
    "name": "Mahesh",
    "age": 25,
    "city": "Bangalore",
    "country": "India"
},
{
    "id": 2,
    "name": "Alex",
    "age": 26,
    "city": "London",
    "country": "UK"
},
{
    "id": 3,
    "name": "David",
    "age": 27,
    "city": "San Franscisco",
    "country": "US"
},
{
    "id": 4,
    "name": "Jonh",
    "age": 28,
    "city": "Toronto",
    "country": "Canada"
},
{
    "id": 5,
    "name": "Chris",
    "age": 29,
    "city": "Paris",
    "country": "France"
},
]

app = Flask(__name__)
run_with_ngrok(app)

@app.route("/")

def home():
  """
  Pagina Inicial
  """
  return "<h3>Chcek to put ADD '/input' To URL and to check out put '/output' to the url</h3>"

@app.route("/input")

def input():
  return jsonify(data)

@app.route("/output", methods=['GET', 'POST'])

def predJson():
  pred = rk.choice(["positive", "negative"])
  nd = d
  nd["prediction"]=pred
  return jsonify(nd)

app.run()